import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import Swal from 'sweetalert2';
import { GoogleGenAI } from '@google/genai';

// ============================================================
// COMPONENT: App (ENCRYPTION ORCHESTRATOR)
// This standalone component manages the UI and logic for 
// cryptographic ciphers (Caesar and Atbash) integrated with 
// AI for semantic filtering of brute-force results.
// ============================================================
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './app.html',
  styleUrl: './app.css'
})
export class App {
  // Global title for the application state
  protected readonly title = signal('Encryption Tool');

  // Input and output state management
  initialText: string = "";
  resultText: Array<string> = [];

  // Storage for the semantically correct result identified by AI
  resultadosProbables: Array<string> = [];

  // Cipher configuration settings
  method: 'cesar' | 'atbash' = 'cesar';
  alphabet: string = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  displacement: number = 3;

  // Sensitive data: Gemini API Key (Security Note: Ideally managed via environment variables)
  private geminiApiKey: string = "";

  // Language Heuristics: Frequency of letters in Spanish for statistical sorting
  private frecuenciasEspanol: { [key: string]: number } = {
    'A': 12.5, 'B': 1.4, 'C': 4.7, 'D': 5.9, 'E': 13.7, 'F': 0.7, 'G': 1.0,
    'H': 0.7, 'I': 6.2, 'J': 0.4, 'K': 0.0, 'L': 5.0, 'M': 3.1, 'N': 6.7,
    'Ñ': 0.3, 'O': 8.7, 'P': 2.5, 'Q': 0.9, 'R': 6.9, 'S': 8.0, 'T': 4.6,
    'U': 3.9, 'V': 0.9, 'W': 0.0, 'X': 0.2, 'Y': 0.9, 'Z': 0.5
  };

  // ============================================================
  // AI ANALYSIS SYSTEM: analizarResultadosConIA
  // What it does: Uses LLM (Gemini) to distinguish valid semantic 
  // data from cryptographic noise.
  // Components used: GoogleGenAI SDK, SweetAlert2 (Swal).
  // Interaction: Scans the 'resultText' array generated by 
  // brute force and identifies the only string that makes sense.
  // ============================================================
  public async analizarResultadosConIA() {
    // Validate that there is content to analyze
    if (this.resultText.length === 0) {
      Swal.fire('Attention', 'You must decrypt a text first to have options to analyze.', 'warning');
      return;
    }

    if (!this.geminiApiKey || this.geminiApiKey === "") {
      Swal.fire('Error', 'Gemini API Key is not configured', 'error');
      return;
    }

    // Visual feedback for the background process
    Swal.fire({
      title: 'Analyzing with AI...',
      text: 'Searching for the hidden message among the digital noise...',
      allowOutsideClick: false,
      didOpen: () => { Swal.showLoading(); }
    });

    try {
      const ai = new GoogleGenAI({ apiKey: this.geminiApiKey });

      // Serialize results array into a single string for AI context
      const listaParaAnalizar = this.resultText.join('\n');

      // Prompt engineering to force a concise, semantic-focused response
      const prompt = `Analyze the following list of strings generated by a cryptographic brute force attack. Almost all are nonsense, but there is ONE that forms real words and makes sense in Spanish. Identify which one it is and respond ONLY with that exact string. Do not add quotes, greetings, or extra explanations.\n\nList to analyze:\n${listaParaAnalizar}`;

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt
      });

      if (response.text) {
        const textoEncontrado = response.text.trim();

        // Isolate the identified result for high-visibility UI rendering
        this.resultadosProbables = [textoEncontrado];

        // Clean up the main noise list by removing the identified valid message
        this.resultText = this.resultText.filter(res => res !== textoEncontrado);
      }

      Swal.close();

    } catch (error) {
      console.error(error);
      Swal.fire('Oops...', 'There was an error connecting with Gemini.', 'error');
    }
  }

  // ============================================================
  // UTILITY: copiarTexto
  // What it does: Copies a specific string to the system clipboard.
  // Components used: Navigator Clipboard API, Swal Toasts.
  // Interaction: Provides user feedback upon success or failure.
  // ============================================================
  public copiarTexto(texto: string) {
    navigator.clipboard.writeText(texto).then(() => {
      Swal.fire({
        toast: true,
        position: 'top-end',
        icon: 'success',
        title: 'Text copied!',
        showConfirmButton: false,
        timer: 2000,
        timerProgressBar: true
      });
    }).catch(err => {
      Swal.fire({
        icon: 'error',
        title: 'Oops...',
        text: 'There was a problem copying the text.',
        confirmButtonColor: '#3498db'
      });
    });
  }

  // ============================================================
  // ALGORITHM: cifrarCesar
  // What it does: Implements the Caesar cipher via modular arithmetic.
  // Components used: Modular alphabet, shift logic.
  // Interaction: If action is 'decrypt', it generates a brute-force 
  // list of all possible shifts in the defined alphabet.
  // ============================================================
  private cifrarCesar(text: string, action: 'cifrar' | 'descifrar'): Array<string> {
    const n = this.alphabet.length;
    let localResults: Array<string> = [];

    // Single execution for standard encryption
    if (action === 'cifrar') {
      const shift = this.displacement;
      const cifrado = text.split('').map((char) => {
        const index = this.alphabet.indexOf(char);
        if (index === -1) return char; // Preserve characters outside alphabet (spaces, etc.)
        const newIndex = (index + (shift % n) + n) % n;
        return this.alphabet[newIndex];
      }).join('');
      localResults.push(cifrado);
    } else {
      // Brute-force approach: Calculate every possible shift
      for (let i: number = 0; i < this.alphabet.length; i++) {
        const shift = -i;
        const descifrado = text.split('').map((char) => {
          const index = this.alphabet.indexOf(char);
          if (index === -1) return char;
          const newIndex = (index + (shift % n) + n) % n;
          return this.alphabet[newIndex];
        }).join('');
        localResults.push(descifrado);
      }
    }
    return localResults;
  }

  // ============================================================
  // ALGORITHM: cifrarAtbash
  // What it does: Implements the Atbash cipher (alphabet reversal).
  // Components used: Array mapping over the alphabet.
  // Interaction: Returns a single mirrored string.
  // ============================================================
  private cifrarAtbash(text: string): string {
    const n = this.alphabet.length;
    return text.split('').map((char) => {
      const index = this.alphabet.indexOf(char);
      if (index === -1) return char;
      // Mirror calculation: (n - 1) - current_index
      const newIndex = (n - 1) - index;
      return this.alphabet[newIndex];
    }).join('');
  }

  // ============================================================
  // DATA ORCHESTRATOR: procesarMensaje
  // What it does: Directs the flow of data between UI inputs and 
  // cryptographic algorithms.
  // Components used: cifrarCesar, cifrarAtbash, frecuenciasEspanol.
  // Interaction: Clears previous states, handles algorithm selection, 
  // and sorts Caesar results by frequency to improve UX.
  // ============================================================
  public procesarMensaje(action: 'cifrar' | 'descifrar') {
    // Reset output buffers
    this.resultText = [];
    this.resultadosProbables = [];

    if (!this.initialText) return;

    if (this.method === 'cesar') {
      let resultados = this.cifrarCesar(this.initialText, action);

      // Heuristic sorting: Move results starting with high-frequency 
      // letters in Spanish to the top.
      if (action === 'descifrar') {
        resultados.sort((a, b) => {
          const primeraLetraA = a.charAt(0).toUpperCase();
          const primeraLetraB = b.charAt(0).toUpperCase();
          const frecA = this.frecuenciasEspanol[primeraLetraA] || 0;
          const frecB = this.frecuenciasEspanol[primeraLetraB] || 0;
          return frecB - frecA;
        });
      }
      this.resultText = resultados;
    } else {
      // Atbash is reciprocal; the logic is the same for encrypt/decrypt
      this.resultText.push(this.cifrarAtbash(this.initialText));
    }
  }
}